spring:
  application:
    name: api-gateway

server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    student-server: /student-server/**

ribbon:
  eureka:
    enabled: true

student-server:
  ribbon:
    listOfServers: http://localhost:2001/,http://localhost:2002/
